spring:
  application:
    name: practice-root
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update   # ← 가장 간단한 해결책
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


server:
  port: 8080